"""Dataset validation + statistics.

Generates a Markdown report at data/VALIDATION.md with:
  - Per-dataset counts, sizes, mean/min/max lengths
  - Distribution stats (family balance, Δτ-sensitive split, etc.)
  - 2-3 sample rendered examples per dataset for hand-verification

Usage:
  uv run python -m data_gen.validate
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

import tiktoken

from data_gen import renderers


REPORT_PATH = Path("data/VALIDATION.md")


def lines_of(path: str) -> int:
    return sum(1 for _ in open(path)) if Path(path).exists() else 0


def sample_examples(path: str, n: int = 3) -> list[dict]:
    if not Path(path).exists():
        return []
    out: list[dict] = []
    with open(path) as f:
        for line in f:
            out.append(json.loads(line))
            if len(out) >= n:
                break
    return out


def validate():
    enc = tiktoken.get_encoding("gpt2")
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

    R: list[str] = ["# IPCN Dataset Validation Report", "", "Generated by `data_gen/validate.py`. All datasets, all stats, plus hand-verification samples.", ""]

    # ---------- Latent World ----------
    R.append("## 1. Temporal Latent World")
    R.append("")
    R.append("| Split | File | Streams |")
    R.append("|---|---|---|")
    for split in ["train_1k", "train_2k", "train_4k", "train_8k",
                  "test_16k", "test_32k", "test_64k", "test_128k",
                  "valid_1k", "valid_4k", "valid_16k"]:
        path = f"data/latent_world/{split}.jsonl"
        n = lines_of(path)
        R.append(f"| {split} | {path} | {n} |")
    R.append("")

    # Δτ-sensitive split on train_1k
    streams = []
    if Path("data/latent_world/train_1k.jsonl").exists():
        with open("data/latent_world/train_1k.jsonl") as f:
            for i, line in enumerate(f):
                if i >= 1000: break
                streams.append(json.loads(line))
    if streams:
        n_ds = sum(1 for s in streams for q in s["questions"] if q["duration_sensitive"])
        n_di = sum(1 for s in streams for q in s["questions"] if not q["duration_sensitive"])
        R.append(f"**Question Δτ-sensitivity (train_1k, first 1000 streams):** "
                 f"{n_ds} sensitive, {n_di} insensitive ({100*n_ds/(n_ds+n_di):.1f}% sensitive).")
        R.append("")

    R.append("### Sample (train_1k[0]) — canonical render")
    R.append("```")
    samples = sample_examples("data/latent_world/train_1k.jsonl", 1)
    if samples:
        R.append(renderers.render_latent_world(samples[0])[:2500])
    R.append("```")
    R.append("")

    # ---------- Ambiguity ----------
    R.append("## 2. Memory-Biased Ambiguity Suite")
    R.append("")
    for split in ["train", "valid"]:
        path = f"data/ambiguity/{split}.jsonl"
        n = lines_of(path)
        R.append(f"- **{split}**: {n} examples ({path})")
    R.append("")

    # Family balance
    if Path("data/ambiguity/train.jsonl").exists():
        fam_counter: Counter[str] = Counter()
        ans_counter: Counter[str] = Counter()
        memstate_counter: Counter[str] = Counter()
        with open("data/ambiguity/train.jsonl") as f:
            for line in f:
                ex = json.loads(line)
                fam_counter[ex["family"]] += 1
                ans_counter[ex["correct_answer"]] += 1
                memstate_counter[ex["memory_state_id"]] += 1
        R.append("**Family balance (train):**")
        for fam, c in fam_counter.most_common():
            R.append(f"- {fam}: {c}")
        R.append("")
        R.append("**Correct-answer distribution (train):**")
        for ans, c in sorted(ans_counter.items()):
            R.append(f"- {ans}: {c}")
        R.append("")
        R.append("**Memory-state distribution (train):**")
        for ms, c in memstate_counter.most_common():
            R.append(f"- {ms}: {c}")
        R.append("")

    R.append("### Sample (train[0]) — canonical render")
    R.append("```")
    samples = sample_examples("data/ambiguity/train.jsonl", 1)
    if samples:
        R.append(renderers.render_ambiguity(samples[0]))
    R.append("```")
    R.append("")

    # ---------- Consolidation ----------
    R.append("## 3. Consolidation Ladder")
    R.append("")
    path = "data/consolidation/ladder_train.jsonl"
    n = lines_of(path)
    R.append(f"- **train**: {n} rules ({path})")
    R.append("")

    if Path(path).exists():
        type_counter: Counter[str] = Counter()
        queries_per_rule: list[int] = []
        with open(path) as f:
            for line in f:
                rule = json.loads(line)
                type_counter[rule["rule_id"].split(".")[0]] += 1
                queries_per_rule.append(len(rule["query_chunks"]))
        R.append("**Rule-type distribution:**")
        for t, c in type_counter.most_common():
            R.append(f"- {t}: {c}")
        R.append("")
        if queries_per_rule:
            R.append(f"**Queries per rule:** min={min(queries_per_rule)}, "
                     f"max={max(queries_per_rule)}, mean={sum(queries_per_rule)/len(queries_per_rule):.0f}")
            R.append("")

    R.append("### Sample (train[0]) — canonical render (first 2000 chars)")
    R.append("```")
    samples = sample_examples(path, 1)
    if samples:
        R.append(renderers.render_consolidation(samples[0])[:2000])
    R.append("```")
    R.append("")

    # ---------- Chronometric pairs ----------
    R.append("## 4. Chronometric Pairs (Prediction 6 eval)")
    R.append("")
    path = "data/chronometric_pairs/pairs.jsonl"
    n = lines_of(path)
    R.append(f"- **pairs**: {n} pairs ({path})")
    R.append("")

    if Path(path).exists():
        deltas_real: list[float] = []
        ds_count = 0
        with open(path) as f:
            for line in f:
                pair = json.loads(line)
                deltas_real.append(pair["delta_tau_real_minutes"])
                if pair["duration_sensitive_q"]["duration_sensitive"]:
                    ds_count += 1
        R.append(f"**Δτ_real distribution:** min={min(deltas_real):.0f}, "
                 f"max={max(deltas_real):.0f}, mean={sum(deltas_real)/len(deltas_real):.0f} min")
        R.append(f"**Pairs with truly Δτ-sensitive question:** {ds_count}/{n} ({100*ds_count/n:.1f}%)")
        R.append("")

    # ---------- Contradiction pairs ----------
    R.append("## 5. Contradiction Pairs (Prediction 7 eval)")
    R.append("")
    path = "data/contradiction_pairs/pairs.jsonl"
    n = lines_of(path)
    R.append(f"- **pairs**: {n} pairs ({path})")
    R.append("")

    if Path(path).exists():
        family_pairs_counter: Counter[tuple] = Counter()
        with open(path) as f:
            for line in f:
                pair = json.loads(line)
                key = (pair["memory_state_a_id"].split(".")[0],)
                family_pairs_counter[key] += 1
        R.append("**Family distribution:**")
        for k, c in family_pairs_counter.most_common():
            R.append(f"- {k[0]}: {c}")
        R.append("")

    R.append("### Sample (pairs[0]) — both arms")
    R.append("```")
    samples = sample_examples(path, 1)
    if samples:
        R.append("=== Memory A, ambiguous input ===")
        R.append(renderers.render_contradiction_pair(samples[0], "mem_a_amb"))
        R.append("\n=== Memory B, ambiguous input ===")
        R.append(renderers.render_contradiction_pair(samples[0], "mem_b_amb"))
        R.append("\n=== Memory A, explicit input ===")
        R.append(renderers.render_contradiction_pair(samples[0], "mem_a_exp"))
    R.append("```")
    R.append("")

    # ---------- Real text ----------
    R.append("## 6. Real Text (Gutenberg)")
    R.append("")
    path = "data/real_text/gutenberg.jsonl"
    n = lines_of(path)
    R.append(f"- **gutenberg**: {n} chunks ({path})")
    R.append("")

    if Path(path).exists():
        token_counts: list[int] = []
        with open(path) as f:
            for line in f:
                chunk = json.loads(line)
                if chunk.get("token_count"):
                    token_counts.append(chunk["token_count"])
        if token_counts:
            R.append(f"**Token-count per chunk:** min={min(token_counts)}, "
                     f"max={max(token_counts)}, mean={sum(token_counts)/len(token_counts):.0f}, "
                     f"total={sum(token_counts):,} tokens")
            R.append("")

    R.append("### Sample (chunks[0]) — first 500 chars")
    R.append("```")
    samples = sample_examples(path, 1)
    if samples:
        R.append(samples[0]["text"][:500])
    R.append("```")
    R.append("")

    # ---------- Tokenized summary if present ----------
    summary_path = Path("data/tokenized/SUMMARY.json")
    if summary_path.exists():
        R.append("## 7. Tokenized Binary Caches")
        R.append("")
        with open(summary_path) as f:
            tsum = json.load(f)
        R.append("| Cache | Examples | Tokens | Mean tokens/ex |")
        R.append("|---|---|---|---|")
        for prefix, meta in tsum.items():
            R.append(f"| {prefix} | {meta['n_examples']} | {meta['n_tokens']:,} | {meta['mean_tokens_per_example']:.0f} |")
        total_tok = sum(m["n_tokens"] for m in tsum.values())
        total_ex = sum(m["n_examples"] for m in tsum.values())
        R.append("")
        R.append(f"**TOTAL: {total_ex} examples, {total_tok:,} tokens across {len(tsum)} caches.**")
        R.append("")

    with open(REPORT_PATH, "w") as f:
        f.write("\n".join(R))
    print(f"Wrote validation report to {REPORT_PATH}")


if __name__ == "__main__":
    validate()
