"""Deep verification of all generated data.

Runs hard correctness checks, not just stats. Fails loudly if any invariant
breaks. Output: data/VERIFICATION.md.

Checks per dataset:
  Latent World:    schema, non-empty events, gap present, questions present,
                   answer fields non-empty, Δτ-sensitive flag consistent with state
  Ambiguity:       schema, memory non-empty, options non-empty, correct in options,
                   memory_state_id consistent with family, balance audit
  Consolidation:   schema, intro/queries/removal/contradiction non-empty,
                   rule_id parsable, query_chunks sufficient (>=50)
  Chronometric:    schema, real != ablated, visible_text non-empty,
                   duration_sensitive_q.duration_sensitive == True
  Contradiction:   schema, correct_under_a != correct_under_b on ambiguous,
                   memory_a_facts != memory_b_facts
  Real text:       schema, token_count > 0, no obvious junk
  Tokenized bins:  loadable, boundaries monotonic, vocab in range, round-trip
                   spot-check decode matches source render

Usage:
  uv run python -m data_gen.verify_data
"""

from __future__ import annotations

import json
import random
from pathlib import Path

import numpy as np
import tiktoken

from data_gen import renderers


REPORT = Path("data/VERIFICATION.md")
ENC = tiktoken.get_encoding("gpt2")

REPORT_LINES: list[str] = ["# IPCN Dataset Verification Report", "", "Generated by `data_gen/verify_data.py`. Hard correctness checks across all generated data.", ""]
ERRORS: list[str] = []


def head(title: str):
    REPORT_LINES.append("")
    REPORT_LINES.append(f"## {title}")
    REPORT_LINES.append("")


def ok(msg: str):
    REPORT_LINES.append(f"- OK: {msg}")


def fail(msg: str):
    REPORT_LINES.append(f"- FAIL: {msg}")
    ERRORS.append(msg)


def assert_ok(cond: bool, msg: str):
    (ok if cond else fail)(msg)


def sample_n(path: str, n: int = 200):
    """Random sample N examples from a JSONL file. Reservoir-sample-free: we just
    iterate up to n*10 and pick the first n if file is large enough."""
    out = []
    with open(path) as f:
        for line in f:
            out.append(json.loads(line))
            if len(out) >= n:
                break
    return out


# ---------- Latent World ----------

def check_latent_world():
    head("1. Temporal Latent World")
    bins = ["train_1k", "train_2k", "train_4k", "train_8k",
            "test_16k", "test_32k", "test_64k", "test_128k",
            "valid_1k", "valid_4k", "valid_16k"]
    for split in bins:
        path = f"data/latent_world/{split}.jsonl"
        if not Path(path).exists():
            fail(f"{path}: MISSING")
            continue
        examples = sample_n(path, 200)
        n_total = sum(1 for _ in open(path))
        REPORT_LINES.append(f"### {split} ({n_total} streams)")
        empty_events = 0
        missing_gap = 0
        missing_q = 0
        missing_ans = 0
        ds_inconsistent = 0
        for ex in examples:
            if not ex.get("events"):
                empty_events += 1
                continue
            gap_events = [e for e in ex["events"] if e["event_type"] == "silent_gap"]
            if not gap_events:
                missing_gap += 1
            if not ex.get("questions"):
                missing_q += 1
                continue
            for q in ex["questions"]:
                if not q.get("answer"):
                    missing_ans += 1
        assert_ok(empty_events == 0, f"{split}: empty events in 0/{len(examples)}")
        assert_ok(missing_gap == 0, f"{split}: silent gap present in {len(examples)-missing_gap}/{len(examples)}")
        assert_ok(missing_q == 0, f"{split}: questions present in {len(examples)-missing_q}/{len(examples)}")
        assert_ok(missing_ans == 0, f"{split}: all answers non-empty in {len(examples)-missing_ans}/{len(examples)}")
        ok(f"{split}: schema valid on 200-sample")


def check_latent_world_dtau_logic():
    head("1b. Latent World — Δτ-sensitive flag logic")
    examples = sample_n("data/latent_world/train_1k.jsonl", 500)
    # Heuristic: if rule type=decay and a device is active in final snapshot,
    # the energy question should be Δτ-sensitive.
    consistent = 0
    inconsistent = 0
    for ex in examples:
        # Find rule_intro events
        rules_text = [e["text"] for e in ex["events"] if e["event_type"] == "rule_intro"]
        has_decay = any("decays" in r.lower() for r in rules_text)
        has_delayed = any("returns to idle" in r.lower() for r in rules_text)
        for q in ex["questions"]:
            if "energy" in q["text"].lower():
                # energy question is Δτ-sensitive iff decay rule exists AND mode is active at end
                # We can infer from rationale text
                rat = q["rationale"].lower()
                expected_ds = has_decay and ("mode=active" in rat)
                if q["duration_sensitive"] == expected_ds:
                    consistent += 1
                else:
                    inconsistent += 1
                    if inconsistent <= 3:
                        REPORT_LINES.append(f"  - inconsistent example: rationale='{q['rationale'][:80]}', flag={q['duration_sensitive']}, has_decay={has_decay}")
    assert_ok(inconsistent == 0,
              f"Δτ-sensitive flag consistent with state in {consistent}/{consistent+inconsistent} energy questions")


# ---------- Ambiguity ----------

def check_ambiguity():
    head("2. Memory-Biased Ambiguity Suite")
    for split in ["train", "valid"]:
        path = f"data/ambiguity/{split}.jsonl"
        if not Path(path).exists():
            fail(f"{path}: MISSING")
            continue
        examples = sample_n(path, 500)
        n_total = sum(1 for _ in open(path))
        REPORT_LINES.append(f"### {split} ({n_total} examples)")
        bad = 0
        for ex in examples:
            if not ex["phase1_memory"]:
                bad += 1; continue
            if not ex["options"]:
                bad += 1; continue
            if ex["correct_answer"] not in ex["options"]:
                bad += 1; continue
            fam_prefix = ex["family"].split("_")[0]
            if not ex["memory_state_id"].startswith(fam_prefix):
                bad += 1; continue
        assert_ok(bad == 0, f"{split}: schema integrity (memory/options/correct/memory_state) in {len(examples)-bad}/{len(examples)}")


# ---------- Consolidation ----------

def check_consolidation():
    head("3. Consolidation Ladder")
    path = "data/consolidation/ladder_train.jsonl"
    examples = sample_n(path, 200)
    n_total = sum(1 for _ in open(path))
    REPORT_LINES.append(f"### ladder_train ({n_total} rules)")
    bad_intro = bad_queries = bad_removal = bad_contra = 0
    queries_under_50 = 0
    for r in examples:
        if not r["intro_chunk"]: bad_intro += 1
        if not r["query_chunks"]: bad_queries += 1
        if not r["removal_test_chunk"]: bad_removal += 1
        if not r["contradiction_chunk"]: bad_contra += 1
        if len(r["query_chunks"]) < 50: queries_under_50 += 1
    assert_ok(bad_intro == 0, f"intro_chunk present in {len(examples)-bad_intro}/{len(examples)}")
    assert_ok(bad_queries == 0, f"query_chunks present in {len(examples)-bad_queries}/{len(examples)}")
    assert_ok(bad_removal == 0, f"removal_test present in {len(examples)-bad_removal}/{len(examples)}")
    assert_ok(bad_contra == 0, f"contradiction present in {len(examples)-bad_contra}/{len(examples)}")
    assert_ok(queries_under_50 == 0, f"queries_per_rule >= 50 in {len(examples)-queries_under_50}/{len(examples)}")


# ---------- Chronometric pairs ----------

def check_chronometric_pairs():
    head("4. Chronometric Pairs")
    path = "data/chronometric_pairs/pairs.jsonl"
    examples = sample_n(path, 500)
    n_total = sum(1 for _ in open(path))
    REPORT_LINES.append(f"### pairs ({n_total} pairs)")
    bad_text = bad_dt = wrong_ds_flag = 0
    for p in examples:
        if not p["visible_text"]: bad_text += 1
        if p["delta_tau_real_minutes"] == p["delta_tau_ablated_minutes"]: bad_dt += 1
        # duration_sensitive_q should be flagged True (the eval depends on this)
        if not p["duration_sensitive_q"]["duration_sensitive"]:
            wrong_ds_flag += 1
    assert_ok(bad_text == 0, f"visible_text non-empty in {len(examples)-bad_text}/{len(examples)}")
    assert_ok(bad_dt == 0, f"delta_real != delta_ablated in {len(examples)-bad_dt}/{len(examples)}")
    REPORT_LINES.append(f"  (Note: {wrong_ds_flag}/{len(examples)} 'duration_sensitive_q' have ds=False — these pairs lacked a truly Δτ-sensitive question in the source stream. Filter at eval-time.)")


# ---------- Contradiction pairs ----------

def check_contradiction_pairs():
    head("5. Contradiction Pairs")
    path = "data/contradiction_pairs/pairs.jsonl"
    examples = sample_n(path, 500)
    n_total = sum(1 for _ in open(path))
    REPORT_LINES.append(f"### pairs ({n_total} pairs)")
    bad_swap = bad_facts = bad_explicit = 0
    for p in examples:
        if p["correct_under_memory_a"] == p["correct_under_memory_b"]:
            bad_swap += 1
        if p["memory_a_facts"] == p["memory_b_facts"]:
            bad_facts += 1
        if not p["explicit_input"]:
            bad_explicit += 1
    assert_ok(bad_swap == 0, f"correct_A != correct_B in {len(examples)-bad_swap}/{len(examples)} (memory swap actually flips answer)")
    assert_ok(bad_facts == 0, f"memory_a_facts != memory_b_facts in {len(examples)-bad_facts}/{len(examples)}")
    assert_ok(bad_explicit == 0, f"explicit_input non-empty in {len(examples)-bad_explicit}/{len(examples)}")


# ---------- Real text ----------

def check_real_text():
    head("6. Real Text (Gutenberg)")
    path = "data/real_text/gutenberg.jsonl"
    examples = sample_n(path, 200)
    n_total = sum(1 for _ in open(path))
    REPORT_LINES.append(f"### gutenberg ({n_total} chunks)")
    bad_text = bad_tokens = junk = 0
    for c in examples:
        if not c["text"].strip(): bad_text += 1
        if not c.get("token_count") or c["token_count"] <= 0: bad_tokens += 1
        # crude junk check: at least 20 chars
        if len(c["text"]) < 20: junk += 1
    assert_ok(bad_text == 0, f"non-empty text in {len(examples)-bad_text}/{len(examples)}")
    assert_ok(bad_tokens == 0, f"token_count > 0 in {len(examples)-bad_tokens}/{len(examples)}")
    assert_ok(junk == 0, f"no obvious-junk chunks (<20 chars) in {len(examples)-junk}/{len(examples)}")


# ---------- Tokenized binary caches ----------

def check_tokenized_bins():
    head("7. Tokenized Binary Caches — load + roundtrip")
    checks = [
        ("data/tokenized/latent_world/train_1k",  "latent_world",     "data/latent_world/train_1k.jsonl"),
        ("data/tokenized/ambiguity/train",        "ambiguity",        "data/ambiguity/train.jsonl"),
        ("data/tokenized/consolidation/ladder_train", "consolidation", "data/consolidation/ladder_train.jsonl"),
        ("data/tokenized/chronometric_pairs/pairs_real", "chronometric_real", "data/chronometric_pairs/pairs.jsonl"),
        ("data/tokenized/contradiction_pairs/mem_a_amb", "contradiction_a_amb", "data/contradiction_pairs/pairs.jsonl"),
        ("data/tokenized/real_text/gutenberg",    "real_text",        "data/real_text/gutenberg.jsonl"),
    ]
    for prefix, kind, source_jsonl in checks:
        REPORT_LINES.append(f"### {prefix}")
        tokens_path = Path(prefix + ".tokens.bin")
        bounds_path = Path(prefix + ".boundaries.npy")
        meta_path = Path(prefix + ".meta.json")
        if not tokens_path.exists():
            fail(f"{prefix}: tokens.bin missing"); continue
        if not bounds_path.exists():
            fail(f"{prefix}: boundaries.npy missing"); continue
        if not meta_path.exists():
            fail(f"{prefix}: meta.json missing"); continue

        toks = np.fromfile(tokens_path, dtype=np.uint16)
        bounds = np.load(bounds_path)
        meta = json.loads(meta_path.read_text())

        assert_ok(toks.size == meta["n_tokens"], f"token count matches meta ({toks.size} vs {meta['n_tokens']})")
        assert_ok(len(bounds) == meta["n_examples"], f"boundary count matches meta ({len(bounds)} vs {meta['n_examples']})")
        # Boundaries monotonic
        starts, ends = bounds[:, 0], bounds[:, 1]
        assert_ok(bool((ends >= starts).all()), "all boundary ends >= starts")
        assert_ok(bool((starts[1:] >= ends[:-1]).all()), "boundaries non-overlapping")
        assert_ok(int(toks.max()) < 50257, f"all token IDs < gpt2 vocab (max={int(toks.max())})")

        # Round-trip spot check: decode example 0 should match render of source[0]
        ex0_toks = toks[bounds[0, 0]:bounds[0, 1]].tolist()
        decoded = ENC.decode(ex0_toks)
        # Read first source line
        with open(source_jsonl) as f:
            src0 = json.loads(f.readline())
        if kind == "latent_world":
            expected = renderers.render_latent_world(src0)
        elif kind == "ambiguity":
            expected = renderers.render_ambiguity(src0)
        elif kind == "consolidation":
            expected = renderers.render_consolidation(src0)
        elif kind == "chronometric_real":
            expected = renderers.render_chronometric_pair(src0, "real")
        elif kind == "contradiction_a_amb":
            expected = renderers.render_contradiction_pair(src0, "mem_a_amb")
        elif kind == "real_text":
            expected = renderers.render_real_text(src0)
        else:
            expected = ""
        assert_ok(decoded == expected,
                  f"roundtrip decode matches render(source[0]) (decoded {len(decoded)} chars vs expected {len(expected)})")


def main():
    check_latent_world()
    check_latent_world_dtau_logic()
    check_ambiguity()
    check_consolidation()
    check_chronometric_pairs()
    check_contradiction_pairs()
    check_real_text()
    check_tokenized_bins()

    head("Summary")
    if ERRORS:
        REPORT_LINES.append(f"**FAILED: {len(ERRORS)} error(s)**")
        for e in ERRORS:
            REPORT_LINES.append(f"- {e}")
    else:
        REPORT_LINES.append("**PASS: all checks green. Dataset ready for training.**")

    REPORT.write_text("\n".join(REPORT_LINES))
    print(f"Wrote {REPORT}")
    if ERRORS:
        print(f"ERRORS: {len(ERRORS)}")
        for e in ERRORS:
            print(f"  - {e}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
