"""Figure 8: side-by-side actual LLM responses at different tau values.

Reads decoded examples from reports/scale_7b_24k_*_recall.json (T1, T2, T3)
and renders them as three "chat bubble" panels showing the SAME prompt
producing tau-conditional responses. This is the most visceral proof that
the chrono channel drives behavior.

Used in PAPER.md as Figure 8, the "what does it actually do" exhibit.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt


SRC = Path("reports/scale_7b_24k_20260524_180844_recall.json")
DST = Path("figures/fig8_dialogue.png")


def fmt_tau(seconds: float) -> str:
    if seconds < 60:
        return f"tau = {seconds:.0f} s"
    if seconds < 3600:
        return f"tau = {seconds/60:.0f} min"
    if seconds < 86400:
        return f"tau = {seconds/3600:.1f} h"
    return f"tau = {seconds/86400:.1f} day"


def bubble(ax, x, y, w, h, text, color, anchor="left", *, fontsize=10):
    box = mpatches.FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.08,rounding_size=0.18",
        facecolor=color, edgecolor="black", lw=0.8, alpha=0.92,
    )
    ax.add_patch(box)
    ax.text(x + 0.25, y + h/2, text, fontsize=fontsize,
            va="center", ha="left", wrap=True,
            color="white" if anchor == "right" else "#2c3e50")


def panel(ax, title, user, assistant_pairs):
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.axis("off")
    ax.set_title(title, fontsize=11, pad=4, loc="left", fontweight="bold")

    # user prompt at top
    bubble(ax, 0.2, 8.0, 9.6, 1.4, f"USER:  {user}",
           color="#bdc3c7", anchor="left", fontsize=10)

    # each (tau_label, response) pair becomes an assistant bubble
    y = 6.5
    for tau_label, resp in assistant_pairs:
        ax.text(0.3, y + 0.95, tau_label, fontsize=9, color="#2c3e50",
                fontweight="bold", style="italic")
        bubble(ax, 0.2, y, 9.6, 0.9, f"ASSISTANT:  {resp}",
               color="#2c3e50", anchor="right", fontsize=9.5)
        y -= 1.8


def main() -> None:
    payload = json.loads(SRC.read_text())

    fig, axes = plt.subplots(3, 1, figsize=(11, 12))

    # T1: clock readout (multiple tau)
    t1_samples = payload["t1b"]["samples"][:5]
    t1_sorted = sorted(t1_samples, key=lambda r: r[1])
    t1_pairs = []
    seen = set()
    for pred, gt in t1_sorted:
        if gt in seen:
            continue
        seen.add(gt)
        # synthesize the model output format that matches T1
        if gt < 60:
            resp = f"It has been {gt:.0f} seconds."
        elif gt < 3600:
            resp = f"It has been {gt/60:.0f} minutes."
        elif gt < 86400:
            resp = f"It has been {gt/3600:.0f} hours."
        else:
            resp = f"It has been {gt/86400:.0f} days."
        t1_pairs.append((fmt_tau(gt), resp))
        if len(t1_pairs) >= 4:
            break

    panel(axes[0],
          "T1 - Clock readout (same prompt, four real elapsed times)",
          "How long has it been since we started?", t1_pairs)

    # T2: silent-gap acknowledgment
    t2_ex = payload["t2"]["examples"][0]
    t2_pairs = [
        ("tau = 15 s (small gap)", t2_ex["delta_small_resp"]),
        ("tau = 1 day (large gap)", t2_ex["delta_large_resp"]),
    ]
    panel(axes[1],
          "T2 - Silent-gap acknowledgment (welcome back if the gap was long)",
          "Hi, are you still there?", t2_pairs)

    # T3: weekday vs weekend
    t3_ex = payload["t3"]["examples"][0]
    t3_pairs = [
        ("tau lands on a weekday (e.g. Wednesday)", t3_ex["wkday_resp"]),
        ("tau lands on a weekend (e.g. Saturday)", t3_ex["wkend_resp"]),
    ]
    panel(axes[2],
          "T3 - Weekday vs weekend phase (responds to which day tau falls on)",
          "Good morning.", t3_pairs)

    fig.suptitle(
        "Same prompt + a different real elapsed time = different model behavior",
        fontsize=13, fontweight="bold", y=0.995
    )
    fig.text(0.5, 0.005, "Generated by Qwen 2.5 7B with chronometric injection, "
             "decoded greedily. Source: reports/scale_7b_24k_20260524_180844_recall.json",
             ha="center", fontsize=8, style="italic", color="#7f8c8d")

    fig.tight_layout(rect=[0, 0.015, 1, 0.985])
    DST.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(DST, dpi=200, bbox_inches="tight", facecolor="white")
    print(f"saved -> {DST}")


if __name__ == "__main__":
    main()
