"""Figure 8: side-by-side REAL LLM responses at different tau values.

Three stacked panels. T1 reads REAL greedy decodes from real_t1_multi_tau.json
(generated by scripts/real_t1_multi_tau.py on the v15 seed 0 release checkpoint).
T2 + T3 read real examples from the 7B-24K recall JSON. No synthesized text.

This is the most visceral proof that the chronometric channel drives behavior:
identical prompt, different tau, different actual model output.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt


T1_SRC = Path("reports/real_t1_multi_tau.json")
T2T3_SRC = Path("reports/scale_7b_24k_20260524_180844_recall.json")
DST = Path("figures/fig8_dialogue.png")


def fmt_tau(seconds: float) -> str:
    if seconds < 60:
        return f"tau = {seconds:.0f} s"
    if seconds < 3600:
        return f"tau = {seconds/60:.0f} min"
    if seconds < 86400:
        return f"tau = {seconds/3600:.1f} h"
    return f"tau = {seconds/86400:.1f} day"


def bubble(ax, x, y, w, h, text, *, color, text_color):
    ax.add_patch(mpatches.FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.08,rounding_size=0.22",
        facecolor=color, edgecolor="black", lw=0.7, alpha=0.95,
    ))
    ax.text(x + 0.30, y + h/2, text, fontsize=10,
            va="center", ha="left", color=text_color)


def panel(ax, title, user, assistant_pairs, *, bubble_h=0.70, gap=1.60,
          tau_offset=1.30):
    n = len(assistant_pairs)
    ax.set_xlim(0, 12)
    needed = 1.3 + 0.45 + n * gap + 0.2
    ax.set_ylim(0, needed)
    ax.axis("off")
    ax.set_title(title, fontsize=11.5, pad=4, loc="left", fontweight="bold")

    # user prompt at top
    top_y = ax.get_ylim()[1] - 1.20
    bubble(ax, 0.2, top_y, 11.6, 0.80, f"USER:  {user}",
           color="#dfe6ea", text_color="#2c3e50")

    y = top_y - 0.40
    for tau_label, resp in assistant_pairs:
        # tau label sits in the gap with clear separation from bubble below
        ax.text(0.30, y - 0.15, tau_label, fontsize=9, color="#16a085",
                fontweight="bold", style="italic")
        bubble(ax, 0.2, y - tau_offset, 11.6, bubble_h,
               f"ASSISTANT:  {resp}",
               color="#2c3e50", text_color="white")
        y -= gap


def load_t1_real() -> list[tuple[str, str]]:
    if not T1_SRC.exists():
        # fallback: only show the one real anchor from T1 examples
        d = json.loads(T2T3_SRC.read_text())
        gt = d["t1"]["examples"][0][2]
        resp = d["t1"]["examples"][0][1]
        return [(fmt_tau(gt), resp)]
    data = json.loads(T1_SRC.read_text())
    out = []
    for s in data["samples"]:
        tau = float(s["tau_seconds"])
        resp = s["response"].strip()
        out.append((fmt_tau(tau), resp))
    return out


def main() -> None:
    t1_pairs = load_t1_real()[:5]  # cap at 5 panels for layout
    t2t3 = json.loads(T2T3_SRC.read_text())
    t2_ex = t2t3["t2"]["examples"][0]
    t3_ex = t2t3["t3"]["examples"][0]

    t2_pairs = [
        ("tau = 15 s (small gap)", t2_ex["delta_small_resp"]),
        ("tau = 1 day (large gap)", t2_ex["delta_large_resp"]),
    ]
    t3_pairs = [
        ("tau lands on a weekday (e.g. Wednesday)", t3_ex["wkday_resp"]),
        ("tau lands on a weekend (e.g. Saturday)", t3_ex["wkend_resp"]),
    ]

    # Panel heights proportional to bubble counts
    h1 = 1.3 + 0.45 + len(t1_pairs) * 1.40 + 0.2
    h2 = 1.3 + 0.45 + len(t2_pairs) * 1.40 + 0.2
    h3 = 1.3 + 0.45 + len(t3_pairs) * 1.40 + 0.2
    total = h1 + h2 + h3

    fig = plt.figure(figsize=(13, total * 0.55))
    gs = fig.add_gridspec(3, 1, height_ratios=[h1, h2, h3], hspace=0.15)
    ax1, ax2, ax3 = (fig.add_subplot(gs[i]) for i in range(3))

    panel(ax1, "T1 - Clock readout (same prompt, multiple real elapsed times)",
          "How long has it been since we started?", t1_pairs)
    panel(ax2, "T2 - Silent-gap acknowledgment (welcome back if the gap was long)",
          "Hi, are you still there?", t2_pairs)
    panel(ax3, "T3 - Weekday vs weekend phase (responds to which day tau falls on)",
          "Good morning.", t3_pairs)

    fig.suptitle(
        "Same prompt + a different real elapsed time = different model behavior",
        fontsize=14, fontweight="bold", y=0.995,
    )
    fig.text(0.5, 0.005,
             "T1: greedy decoding of v15 seed 0 checkpoint at six tau values "
             "(reports/real_t1_multi_tau.json). "
             "T2 + T3: real examples from reports/scale_7b_24k_20260524_180844_recall.json. "
             "No synthesized text.",
             ha="center", fontsize=8, style="italic", color="#7f8c8d")

    fig.tight_layout(rect=[0, 0.015, 1, 0.97])
    DST.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(DST, dpi=200, bbox_inches="tight", facecolor="white")
    print(f"saved -> {DST}")


if __name__ == "__main__":
    main()
